# Generated by Django 3.2 on 2023-03-22 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_auto_20230322_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='введите текст отзыва', verbose_name='текст отзыва')),
                ('score', models.PositiveSmallIntegerField(help_text='поставьте оценку произведению', verbose_name='оценка произведения')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='введите дату отзыва', verbose_name='дата отзыва')),
                ('author', models.ForeignKey(help_text='укажите автора', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='автор отзыва')),
                ('title', models.ForeignKey(help_text='введите название произведения', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.title', verbose_name='произведение с отзывом')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
